TravelBlog/TravelBlog/TravelBlog/Controllers/AdminCommentController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using TravelBlog.Entity;

namespace TravelBlog.Controllers
{
    public class AdminCommentController : Controller
    {
        DataContext db=new DataContext();
        // GET: AdminComment
        public ActionResult Index()
        {
            var comments = db.BlogComments.Include("User").ToList();
            return View(comments);

        }
        [HttpPost]
        public ActionResult ApproveComment(int id, bool isApproved)
        {
            var comment = db.BlogComments.Find(id);
            if (comment != null)
            {
                comment.IsApproved = isApproved;
                db.SaveChanges();
            }

            return RedirectToAction("Index");
        }
    }
}

TravelBlog/TravelBlog/TravelBlog/Views/AdminComment/Index.cshtml
@model IEnumerable<TravelBlog.Models.BlogComments>

@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_LayoutPanel.cshtml";
}

<h2>Comments</h2>

<table class="table">
    <thead>
        <tr>
            <th>Kullanıcı Adı</th>
            <th>Yorum</th>
            <th>Onay Durumu</th>
            <th></th>
        </tr>
    </thead>
    <tbody>
        @foreach (var comment in Model)
        {
            <tr>
                <td>@comment.User.userName</td>
                <td>@comment.comment</td>
                <td>@comment.IsApproved</td>
                <td>
                    @using (Html.BeginForm("ApproveComment", "AdminComment", new { id = comment.Id }))
                    {
                        @Html.CheckBox("isApproved", comment.IsApproved)
                        <button class="btn btn-warning btn-sm" type="submit">Onayla</button>
                    }
                </td>
            </tr>
        }
    </tbody>
</table>