TravelBlog/TravelBlog/TravelBlog/Controllers/UserBlogController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using TravelBlog.Entity;
using TravelBlog.Models;
using TravelBlog.Models.ViewModel;

namespace TravelBlog.Controllers
{
    public class UserBlogController : Controller
    {
        private DataContext db = new DataContext();

        // GET: UserBlog
        public ActionResult Index()
        {
            var loggedInUser = Session["LoggedInUser"] as User;
            ViewBag.LoggedInUser = loggedInUser;

            var blog = db.Blog.Include(b => b.User).Where(b=>b.UserId==loggedInUser.Id);
        
            if (loggedInUser == null)
            {
                return RedirectToAction("Index","Login");
            }
            else
            {
                return View(blog.ToList());
            }

        }

        // GET: UserBlog/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Blog blog = db.Blog.Find(id);
            if (blog == null)
            {
                return HttpNotFound();
            }
            return View(blog);
        }

        // GET: UserBlog/Create
        public ActionResult Create()
        {
            var viewModel = new BlogCreateViewModel
            {
                Blog = new Blog(),
                Users = new SelectList(db.User, "Id", "Name"),
                Cities = new SelectList(db.City, "Id", "Name")
            };
            // Giriş yapmış kullanıcının bilgilerini al
            var loggedInUser = Session["LoggedInUser"] as User;
            ViewBag.LoggedInUser = loggedInUser;
            return View(viewModel);
        }

        // POST: UserBlog/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(BlogCreateViewModel viewModel)
        {
            if (ModelState.IsValid)
            {
                // Giriş yapmış kullanıcının bilgilerini al
                var loggedInUser = Session["LoggedInUser"] as User;

               
                // Eğer giriş yapmış bir kullanıcı varsa, UserId'yi bu kullanıcının Id'si olarak ayarla
                if (loggedInUser != null)
                {
                    viewModel.Blog.UserId = loggedInUser.Id;
                }
                else
                {
                    // Kullanıcı giriş yapmamışsa veya bilgileri alınamamışsa bir hata mesajı göster
                    ModelState.AddModelError("", "Kullanıcı bilgileri alınamadı.");
                    ViewBag.UserId = new SelectList(db.User, "Id", "Surname", viewModel.Blog.UserId);
                    return View(viewModel.Blog);
                }
                var bl=viewModel.Blog;
                viewModel.Blog.UserId=loggedInUser.Id;
                viewModel.Blog.postDate = DateTime.Now;
                viewModel.Blog.IsDelete = false;
                viewModel.Blog.IsStatus = true;
                var ornek=viewModel.Blog;

                db.Blog.Add(viewModel.Blog);
                db.SaveChanges();

                // Blog ve City arasındaki ilişkiyi oluşturmak için yeni bir BlogCityRelations girişi ekleyin
                var blogCityRelation = new BlogCityRelations
                {
                    BlogId = viewModel.Blog.Id, // Yeni oluşturulan blogun Id'sini kullanabilirsiniz
                    CityId = viewModel.SelectedCityId
                };

                db.BlogCityRelations.Add(blogCityRelation);
                db.SaveChanges();

                return RedirectToAction("Index");
            }

            ViewBag.UserId = new SelectList(db.User, "Id", "Surname", viewModel.Blog.UserId);
            return View(viewModel.Blog);
        }

        // GET: UserBlog/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Blog blog = db.Blog.Find(id);
            if (blog == null)
            {
                return HttpNotFound();
            }
            ViewBag.UserId = new SelectList(db.User, "Id", "Surname", blog.UserId);
            return View(blog);
        }

        // POST: UserBlog/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "Id,title,content,likeNumbers,postDate,UserId,Name,Description,Image,IsStatus,IsDelete")] Blog blog)
        {
            if (ModelState.IsValid)
            {
                db.Entry(blog).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            ViewBag.UserId = new SelectList(db.User, "Id", "Surname", blog.UserId);
            return View(blog);
        }

        // GET: UserBlog/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Blog blog = db.Blog.Find(id);
            if (blog == null)
            {
                return HttpNotFound();
            }
            return View(blog);
        }

        // POST: UserBlog/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Blog blog = db.Blog.Find(id);
            db.Blog.Remove(blog);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

TravelBlog/TravelBlog/TravelBlog/Controllers/UserDashboardController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using TravelBlog.Entity;
using TravelBlog.Models;

namespace TravelBlog.Controllers
{
    public class UserDashboardController : Controller
    {
        DataContext db=new DataContext();
        // GET: UserDashboard
        public ActionResult Index()
        {
            var loggedInUser = Session["LoggedInUser"] as User;
            ViewBag.LoggedInUser = loggedInUser;

            if(loggedInUser != null)
            {
                // Kullanıcının blogları
                var userBlogs = db.Blog.Where(b => b.UserId == loggedInUser.Id).ToList();

                // Kullanıcının beğendiği blog sayısı
                var likedBlogsCount = db.BlogLikeRelations.Count(bl => bl.UserId == loggedInUser.Id);

                // Kullanıcının hangi şehirler için blog oluşturduğu
                var citiesForBlogs = db.City
                    .Where(c => db.BlogCityRelations.Any(bc => bc.Blog.UserId == loggedInUser.Id && bc.CityId == c.Id))
                    .ToList();

                ViewBag.LikedBlogsCount = likedBlogsCount;
                ViewBag.CitiesForBlogs = citiesForBlogs.Count();

                return View(userBlogs);
            }
            else
            {   
                return RedirectToAction("Index","Login");
            }
            
            
        }
    }
}

TravelBlog/TravelBlog/TravelBlog/Views/UserDashboard/Index.cshtml
@model IEnumerable<TravelBlog.Models.Blog>

@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
}



<header>
    <div class="site-brand text-center">
        <div class="container">
            <a href="index.html">
                <h2>Travel And Share</h2>
            </a>

        </div>
    </div>
    <div class="header-inner">
        <div class="container">
            <div class="row">
                <div class="col-md-9 col-sm-8 col-xs-3 pos-s">
                    <button class="menu-toggle">
                        <span class="bar"></span>
                        <span class="bar"></span>
                        <span class="bar"></span>
                    </button>
                    <nav class="navbar navbar-default">
                        <div class="collapse navbar-collapse">
                            <ul class="nav navbar-nav">
                                <li class="menu-item active">
                                    @Html.ActionLink("Home", "Index", "Home", new { area = "" }, new { @class = "nav-link" })

                                </li>
                                <li class="menu-item dropdown">
                                    <a href="#" data-toggle="dropdown" class="dropdown-toggle" aria-haspopup="true">Pages <span class="caret"></span></a>
                                    <ul role="menu" class=" dropdown-menu">
                                        <li class="menu-item">@Html.ActionLink("Panel", "Index", "Panel", new { area = "" }, new { @class = "nav-link" })</li>
                                        <li class="menu-item">@Html.ActionLink("MyBlogs", "Index", "UserBlog", new { area = "" }, new { @class = "nav-link" })</li>
                                        <li class="menu-item">@Html.ActionLink("My Dashboard", "Index", "UserDashboard", new { area = "" }, new { @class = "nav-link" })</li>

                                    </ul>
                                </li>

                            </ul>
                        </div>
                    </nav>
                </div>
                <div class="col-md-3 col-sm-4 col-xs-9 text-md-center">
                    <div class="search-toggle">

                        <i class="fa fa-search"></i>
                    </div>
                    <ul class="social-icons-menu list-unstyled">
                        <li>
                            @if (ViewBag.LoggedInUser == null)
                            {
                                @Html.ActionLink("Login", "Index", "Login", new { area = "" }, new { @class = "nav-link" })<i class="fa fa-facebook"></i>

                            }
                        </li>
                        <li>
                            @if (ViewBag.LoggedInUser != null)
                            {
                                @ViewBag.LoggedInUser.Name @ViewBag.LoggedInUser.Surname
                                <a href="@Url.Action("Logout", "Login")">
                                    &nbsp;<i class="fa fa-sign-out"></i> Logout
                                </a>
                            }
                        </li>
                    </ul>
                </div>
            </div>
        </div>
    </div>
    <div class="search-area">
        <span class="close-search">
            <i class="fa fa-close"></i>
        </span>
        <div class="display-table">
            <div class="display-table-cell">
                <form role="search" method="get" class="search-form" action="#">
                    <input type="search" class="search-field" placeholder="Search..." name="s" required="required">
                    <button type="submit" class="search-submit"><i class="fa fa-search"></i></button>
                </form>
            </div>
        </div>
    </div>
</header>

<div class="container">
    <div style="background-color: #f5f5f5; width: 25%; margin: 10px; float: left; height: 150px">
        <img src="https://www.markum.com/blog/wp-content/uploads/2017/11/kisisel-blog.jpg" alt="Blog Image" style="width: 100%; height: 170px;">
        <div style="background-color: #f5f5f5; padding: 15px; text-align: center;">
            <span>Blog sayım: @Model.Count() </span>
        </div>
    </div>


    <div style="background-color: #f5f5f5; width: 25%; margin: 10px; float: left; height: 150px">
        <img src="https://cdn.wmaraci.com/nedir/like2.png" alt="Blog Image" style="width: 100%; height: 170px;">

        <div style="background-color: #f5f5f5; padding: 15px; text-align: center;">
            <span>Beğendiğim blog sayısı: @ViewBag.LikedBlogsCount</span>
        </div>
    </div>

    <div style="background-color: #f5f5f5; width: 25%; margin: 10px; float: left; height: 150px">
        <img src="https://www.cities.com/media/img/main-slide/slide-1.jpg" alt="Blog Image" style="width: 100%; height: 170px;">
        <div style="background-color: #f5f5f5; padding: 15px; text-align: center;">
            <span>Gezdiğim il sayısı:  @ViewBag.CitiesForBlogs </span>
        </div>
    </div>


</div>